### ISSUE TITLE
Loading as ES6 Module not possible

### ISSUE THREAD

**Issue by jogibear9988** [GedMarc/bootstrap4-dialog#12]
Hello,

I wanted to load as ES6 Module in the Browser like this:

import '/node_modules/bootstrap4-dialog/dist/js/bootstrap-dialog.js';

but it is not possible, root is undefined in 
bootstrap-dialog.js line 29

I think it is because "this" is not window when you use es6 modules

**Comment by GedMarc** [comment]
We pulled in some AMD stuffs a bit earlier,
Is it possible to attach a reproduction?

On 11 Apr 2019 15:47, Jochen Kühner <notifications@github.com> wrote:

Hello,

I wanted to load as ES6 Module in the Browser like this:

import '/node_modules/bootstrap4-dialog/dist/js/bootstrap-dialog.js';

but it is not possible, root is undefined in
bootstrap-dialog.js line 29

I think it is because "this" is not window when you use es6 modules

**Comment by jogibear9988** [comment]
small repo:

https://github.com/jogibear9988/testBSDialog

**Comment by jogibear9988** [comment]
@GedMarc could you reproduce?

**Comment by GedMarc** [comment]
Been a rough weekend, the work that buys the bread and milk wins :) 
Will take a look as soon as I can, I also have to bump the jQuery version up so it's probably gonna go in line with that
