### ISSUE TITLE
JavaScript cannot run on Remote Page

### ISSUE THREAD

**Issue by Sangjin-Woo** [GedMarc/bootstrap4-dialog#15]
# Remote.html

<script>
	alert("Script OK");
</script>
Hello, this is a message from remote.html!

Works in BootStrap3 but not in BootStrap4.

**Comment by GedMarc** [comment]
Will take a look

**Comment by GedMarc** [comment]
Please post example, this could just be CRP

**Comment by shanu2rick** [comment]
Hello, I have the same issue and @Sangjin-Woo is right about working in v3 and not in v4.

Taking example from https://nakupanda.github.io/bootstrap3-dialog/#loading-remote-page:
```
BootstrapDialog.show({
    message: $('<div></div>').load('remote.html')
});
```

If page remote.html (or any dynamic link) has any javascript/jquery code in it like `<script> alert("Script OK"); </script>` is not working.

Also tried with `$(function () { alert("Script OK"); })` and `$(window).load(function () { alert("Script OK"); })`. 

I think this issue has more to do with [BootstrapModal](https://getbootstrap.com/docs/4.3/components/modal/) rather than this plugin.

Any help would be appreciated.

**Comment by GedMarc** [comment]
Ok, I think there is a little misunderstanding here with how the .load() and jquery method works - as well -the dom is not ready until the final animation action of "shown" is complete

Pointing you to this direction : 
https://bugs.jquery.com/ticket/3733
https://stackoverflow.com/questions/6274362/why-does-jquerys-load-ignore-script
https://forum.jquery.com/topic/jquery-removing-script-tags-from-html-string-when-using-html
https://api.jquery.com/jQuery.getScript/ 


Try 
```
BootstrapDialog.show({
    message: $('<div></div>').load('remote.html'),
     onshown: function(){alert('displayed');}
});
```

**Comment by shanu2rick** [comment]
Thanks for your reply. Your solution works as suggested but I am still curious why was it working in Bootstrap v3? This [link](https://stackoverflow.com/a/6274527) says `$.load()` still register scripts after content is loaded into the DOM.

**Comment by shanu2rick** [comment]
Based on @GedMarc's reply and taking inspiration from [this](https://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=loading-content-in-modal-body-via-ajax), I came up with following solution:

```
BootstrapDialog.show({
    message: $('<div id="popupContent"></div>'),
    onshown: function () {
        $("#popupContent").load('remote.html')
    }
})
```
Its a little work around but after this change, all javascript based code in remote.html will work perfectly as it was working in v3.
