### ISSUE TITLE
bootstrap-dialog-close-button not right aligned in dialog

### ISSUE THREAD

**Issue by melvinchia** [GedMarc/bootstrap4-dialog#3]
![image](https://user-images.githubusercontent.com/2408261/42365980-8ff8f7aa-8132-11e8-8d23-432410045925.png)

Description:
As described. (See screenshot above)

Solved by adding this in CSS:
`.bootstrap-dialog-header { width: 100%; }`

![image](https://user-images.githubusercontent.com/2408261/42366287-63b8edac-8133-11e8-8915-9ea210d28c2e.png)

Probable cause:
bootstrap-dialog-header width was equal to its content width.
After changing the bootstrap-dialog-header width to 100%, bootstrap-dialog-close-button was able to right align to the end of the header.

**Comment by GedMarc** [comment]
Hmm I was certain I had done this one already,
Yes it is because of the new classes related to positioning and the flex layout by default.

I'll double check and get back to you

**Comment by melvinchia** [comment]
If using "width: 100%" isn't totally flex-friendly, I found another flex-friendly solution instead:
`.bootstrap-dialog .bootstrap-dialog-header { flex-grow: 1; }`

I'll use the new solution instead of the width one, just to maintain flex-friendliness.. 😂

**Comment by GedMarc** [comment]
Hmm, I'm not sure which version of the plugin you are using - I can't replicate it not being placed properly.

Can you send me a zip of your library so i can compare them?

**Comment by melvinchia** [comment]
Hi Marc,
Sure, zipped it up. Pretty sure its the standard dist copy of 4.1.0 though..

Damn, now Gmail doesn't let me attach zipped files with .js files in them.
I've put it on my dropbox..
https://dl.dropbox.com/s/ymyhsacv2qzcwwd/bootstrap4dialog.zip

**Comment by GedMarc** [comment]
Hi Melvinchia

If you open up the examples and run the index.html, you can see the icon is definitely aligned correctly.
Please make sure you are using the framework according to the examples :)

If you still having a problem with it, please replicate in the examples html,  - Thanks!

**Comment by jarodhanko** [comment]
@GedMarc I cloned your repo, but examples index.html is still using bootstrap 3.  Here is a jsfiddle showing the issue https://jsfiddle.net/tvs3eo9y/1/.  I am using the npm package in the fiddle, but I tested locally as well and see the same issue.

Perhaps you could simply merge in this commit https://github.com/EugenMayer/bootstrap-dialog/commit/2bda5be0dca209fad7283905825afa33e346ff51

**Comment by GedMarc** [comment]
OOOPPPPSSS,

I did it a bit different - safari not so happy with that one.

Added display:contents to the close button for flex layout on the bootstrap header
Repositioned the close button to after the title and removed unecessary css

Please close if happy ;)

Sorry @melvinchia how did I miss that one!

**Comment by GedMarc** [comment]
https://github.com/GedMarc/bootstrap4-dialog/commit/76ea8f190e7a884bcde20ec6950a4b2a070e7514

**Comment by jarodhanko** [comment]
Thanks for the quick fix.  That works for me.  Any chance you could make the close button vertically centered (it's pretty close, but just slightly too far down).

**Comment by GedMarc** [comment]
Ok that's an interesting one - it's actually the character being used, but it's used for, well a decent reason i guess.. A quick google will get you any extra info you want on this - 

The character &times; has a 2px reduction on it's font, and the font-size/line-heights for modals are consistant - but the character is used correctly as X just looks weird in most cases.

Cause of this i'm a bit hesitant to actually change it in the library, it is for all intent and purpose - quite correct. Custom CSS libraries like those big circles on the top right corner won't display right ;)

SO

Here's what I would do, but there's a thousand ways of sorting this out - 

```
.bootstrap-dialog-close-button>.close {
  padding: inherit;margin: inherit;margin-top: -2px;
}
```
The padding and margin inherit remove the custom placement and resolve correctly because bootstrap 4 is using flex - the character will still be in the exact same position with the -1rem in CSS everywhere

The character will still be 2px short on the font, so the placement of the -2px after the inherit will resolve it.

Other ways are like changing the content from &times; to something else, using absolute positioning and applying custom close syntax as well 

![image](https://user-images.githubusercontent.com/5367513/46493562-fb8aa700-c810-11e8-9faf-e3974ce61b16.png)


![image](https://user-images.githubusercontent.com/5367513/46493601-165d1b80-c811-11e8-8a4e-55965a346566.png)

**Comment by jarodhanko** [comment]
I understand.  Thanks for the detailed explanation.  I see that even the bootstrap 4 examples don't vertical align the x (especially if you start changing the size of the title text).  Your css solution will work for my use case, so I'll add that to my custom css.  Thanks again for the quick response.

**Comment by GedMarc** [comment]
Don't forget to star! :)

Thanks for highlighting quite an NB thing - never picked it up always testing with my customs stuffs xD
